- name: Obtener session_id de znuny
  block:
    - name: Znuny login, get session id
      delegate_to: localhost
      run_once: true # noqa: run-once[task]
      ansible.builtin.uri:
        url: "{{ znuny_apis.care.login }}\
          {{ params | ditra.cisco.dict2querystring('?') if params is defined and params }}"
        method: POST
        body_format: json
        body:
          UserLogin: "{{ znuny_user }}"
          Password: "{{ znuny_password }}"
        validate_certs: "{{ validate_certs | default(true)}}"
        return_content: true
      register: response
      failed_when: "response.status != 200 or TicketID is none or 'Error' in response.json"

    - name: Get SessionID from login response
      delegate_to: localhost
      run_once: true # noqa: run-once[task]
      ansible.builtin.set_fact:
        session_id: "{{ r.SessionID }}"
      vars:
        r: "{{ response.content | from_json }}"
  rescue:
    - name: Set errors on login failed
      when: ansible_failed_task.name == 'Znuny login, get session id'
      ansible.builtin.set_fact:
        error_code: "Inicio de sesion fallido"
        error_detail: |
          Response status: {{ response.status }}
          Response error:{{ response.json['Error'] | to_nice_json }}
        log_error: "{{ response }}"
