---

- name: Use template for copy file of configuration
  hosts: "{{ target_host | default('all') }}"
  become: true
  tasks:
    - name: Crear archivo de texto en el directorio home con el mensaje
      ansible.builtin.copy:
        content: "{{ var_text }}"
        dest: "/home/user1/mensaje.txt"
        mode: '0644'
