---
- name: Playbook básico para Windows
  hosts: "{{ target_host | default('all') }}"
  tasks:
    - name: Verificar la conectividad
      ansible.windows.win_ping:

    - name: Crear archivo de texto en el escritorio con el mensaje
      ansible.windows.win_copy:
        content: "{{ var_text }}"
        dest: "C:\\Users\\{{ ansible_user }}\\Desktop\\mensaje.txt"
